[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyzag"
version = "2.0.0"
authors = [
  { name="Mark Messner", email="messner@anl.gov" },
]
description = "A Python package for efficiently solving and taking derivatives of systems of recursive nonlinear equations"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2.0",
    "tqdm",
    "numpy>=2",
    "matplotlib",
    "pyro-ppl",
    "scipy",
]

[project.optional-dependencies]
dev = [
    # testing
    "pytest",
    # lint + format
    "pylint==2.15.5",
    "black==24.3.0",
    # notebooks
    "nbdime",
]

[tool.setuptools.packages.find]
include = ["pyzag*"]
exclude = ["pyzag_original*", "examples*", "docs*", "test*"]

[project.urls]
Homepage = "https://github.com/applied-material-modeling/pyzag"
Issues = "https://github.com/applied-material-modeling/pyzag/issues"
