name: Check code formatting
on: [push, pull_request]
jobs:
      check-formatting:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - run: pip install -r requirements.txt -r dev-requirements.txt
            - run: pylint pyzag
            - run: black --check pyzag test